"""
report_tab.py

Renders the full written Report tab for the Streamlit app - narrative
text + Altair charts, in the order the project actually happened.

Import render_report(st) from app.py and call it inside the Report tab.
"""

import generate_report as R


def render_report(st):
    st.title("Turn Detection: From Synthetic Benchmark to Real-World Adaptation")

    st.markdown("""
This project reproduces pipecat's Smart Turn v3 turn-detection model, discovers a real
generalization gap, and closes part of that gap through targeted fine-tuning on real
conversational audio - while carefully tracking whether that fine-tuning damages what
the model already learned.
""")

    # ---------------------------------------------------------
    st.header("1. Reproducing Pipecat's Smart Turn v3")
    st.markdown(f"""
We rebuilt pipecat's architecture exactly: a Whisper Tiny encoder (resized to an
8-second context window), an attention-pooling layer, and a small MLP classifier -
matching their published hyperparameters (learning rate, cosine schedule, 4 training
epochs) and training on their full **271k-row** `smart-turn-data-v3.2-train` dataset.

**Result: {R.STAGE1_TEST_ACCURACY:.2%} accuracy** on pipecat's own held-out test set,
matching the kind of performance their own reported benchmarks would suggest.
""")

    st.altair_chart(R.chart_stage1_language_accuracy(), use_container_width=True)

    # ---------------------------------------------------------
    st.header("2. A Closer Look at the Training Data")
    st.markdown(f"""
A strong benchmark number is only half the story. Digging into the training data itself
revealed something the accuracy number alone didn't show: **{R.SYNTHETIC_PCT:.0%} of the
training data is synthetic**, generated by text-to-speech engines rather than recorded
from real speakers.

For Hindi specifically, the gap was total: **every single Hindi training example was
TTS-generated - zero real Hindi recordings exist anywhere in the dataset.** Listening to
samples confirmed the TTS audio was clean and even captured genuine code-switching
patterns, but it simply didn't sound like how people actually talk - no natural
disfluency, no real acoustic variation, no cross-talk.
""")

    st.altair_chart(R.chart_synthetic_split(), use_container_width=True)

    st.markdown("""
This raised an obvious question: if the model has only ever heard synthetic speech,
how well does it actually handle real conversations?
""")

    # ---------------------------------------------------------
    st.header("3. Testing on Real Speech: The Generalization Gap")
    st.markdown(f"""
To answer that, we went looking for a dataset of genuine, real-world conversations. We
found **sarvamai/indic-diarbench** - real multi-speaker recordings across 22 Indian
languages, annotated with speaker identity and segment timing, letting us derive
genuine turn-completion labels from real dialogue structure rather than synthetic
sentence construction.

Running the pipecat-reproduction model on this real data, with zero fine-tuning,
produced a stark result:
""")

    st.altair_chart(R.chart_zero_shot_gap(), use_container_width=True)

    st.markdown(f"""
Accuracy dropped from {R.STAGE1_TEST_ACCURACY:.2%} to just **{R.ZERO_SHOT_ACCURACY:.2%}**
- barely better than chance. The model was also heavily biased toward predicting
"complete" (recall {R.ZERO_SHOT_RECALL:.1%} vs. precision {R.ZERO_SHOT_PRECISION:.1%}),
suggesting it had learned "clean audio ending = done" as a shortcut that real,
noisier speech doesn't satisfy. This gap is what motivated the next stage.
""")

    # ---------------------------------------------------------
    st.header("4. Building a Real-Data Training Set")
    st.markdown(f"""
Real multi-speaker recordings are messy - overlapping speech, backchannels
("haan", "hmm"), and cross-talk are constant. Before extracting any training examples,
we ran EDA specifically to understand this: across all 22 languages, roughly **44% of
speaker transitions involved some form of overlap or interruption**.

To get clean labels, we designed a strict extraction rule: a candidate clip is only
used if its entire 8-second audio window contains **no other speaker's real speech** -
same-speaker continuation means "incomplete," a genuine speaker change means
"complete." This deliberately traded quantity for quality.

**Final yield: {R.DIARBENCH_EXTRACTION['total_true'] + R.DIARBENCH_EXTRACTION['total_false_cross'] + R.DIARBENCH_EXTRACTION['total_false_midcut']:,} labeled examples**
across all languages ({R.DIARBENCH_EXTRACTION['hindi_total']:,} for Hindi alone).
""")

    # ---------------------------------------------------------
    st.header("5. Fine-tuning: Adaptation vs. Forgetting")
    st.markdown("""
With real labeled data in hand, we fine-tuned the pipecat-reproduction model at a
deliberately low learning rate. The key question wasn't just "does it improve on real
data" - it was **"does improving on real data come at the cost of what it already
learned?"** So every epoch, we evaluated the model on *both* the new real-data set
*and* the original synthetic test set.
""")

    st.altair_chart(R.chart_forgetting_curve(), use_container_width=True)

    st.markdown(f"""
The result was the outcome we were hoping for: real-data accuracy rose from
{R.ZERO_SHOT_ACCURACY:.2%} to **{R.FORGETTING_CURVE[2]['stage2_accuracy']:.2%}**, while
synthetic-test accuracy dropped only slightly, from {R.STAGE1_TEST_ACCURACY:.2%} to
**{R.FORGETTING_CURVE[2]['stage1_accuracy']:.2%}** - most of that small drop happened in
the first epoch and then stabilized. A large real-world gain, a small and bounded cost.
""")

    # ---------------------------------------------------------
    st.header("6. Final Results")
    st.altair_chart(R.chart_final_2x2(), use_container_width=True)

    col1, col2 = st.columns(2)
    with col1:
        st.altair_chart(R.chart_hindi_improvement(), use_container_width=True)
    with col2:
        st.altair_chart(R.chart_kind_breakdown(), use_container_width=True)

    st.markdown("""
Hindi specifically saw one of the largest gains from fine-tuning. But the breakdown by
case type shows an honest limitation: most of the improvement comes from correctly
identifying obviously mid-utterance clips, while genuine cross-speaker turn-change
discrimination - the harder task - improved less. That remains the model's weakest
point.
""")

    # ---------------------------------------------------------
    st.header("7. Deployment: ONNX Export and Quantization")
    st.markdown("""
Both models were exported to ONNX and quantized to int8 for lighter-weight deployment.
""")

    st.altair_chart(R.chart_quantization(), use_container_width=True)

    st.markdown("""
Quantization shrank both models by roughly 68% with under one point of accuracy loss
on either test set - a favorable tradeoff for CPU deployment.
""")

    # ---------------------------------------------------------
    st.header("Summary")
    st.markdown(f"""
- Reproduced pipecat's Smart Turn v3, achieving **{R.STAGE1_TEST_ACCURACY:.2%}** on their
  synthetic benchmark.
- Found the training data was **{R.SYNTHETIC_PCT:.0%} synthetic**, with zero real Hindi
  audio - and confirmed via zero-shot testing that this produced a real
  **{R.STAGE1_TEST_ACCURACY-R.ZERO_SHOT_ACCURACY:.0%}-point** generalization gap on
  genuine conversational speech.
- Built a real-data fine-tuning set from `sarvamai/indic-diarbench`, using a strict
  clean-audio extraction rule validated through direct EDA of speaker-overlap patterns.
- Fine-tuning closed much of that gap (+{R.FORGETTING_CURVE[2]['stage2_accuracy']-R.ZERO_SHOT_ACCURACY:.0%}
  points) while costing only {R.STAGE1_TEST_ACCURACY-R.FORGETTING_CURVE[2]['stage1_accuracy']:.0%}
  points on the original benchmark.
- Deployed both models as quantized ONNX artifacts with minimal accuracy loss.
- **Remaining limitation**: genuine cross-speaker turn discrimination is still
  meaningfully weaker than mid-utterance detection - the harder half of the task.
""")